services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=contact.forgewrite@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - forgewrite
    restart: unless-stopped

  php:
    build:
      context: ./php
    volumes:
      - ../api:/var/www/api
    environment:
      - APP_ENV=prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.forgewrite.fr`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=9000"
    depends_on:
      - db
    networks:
      - forgewrite
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"

      # Serve le site sur www.forgewrite.fr
      - "traefik.http.routers.front.rule=Host(`www.forgewrite.fr`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=3000"

      # Redirection HTTP forgewrite.fr vers www
      - "traefik.http.routers.redirect-http.rule=Host(`forgewrite.fr`)"
      - "traefik.http.routers.redirect-http.entrypoints=web"
      - "traefik.http.routers.redirect-http.middlewares=redirect-to-www"

      # Redirection HTTPS forgewrite.fr vers www
      - "traefik.http.routers.redirect-https.rule=Host(`forgewrite.fr`)"
      - "traefik.http.routers.redirect-https.entrypoints=websecure"
      - "traefik.http.routers.redirect-https.tls=true"
      - "traefik.http.routers.redirect-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.redirect-https.middlewares=redirect-to-www"

      # Middleware de redirection → https://www.forgewrite.fr
      - "traefik.http.middlewares.redirect-to-www.redirectregex.regex=^https?://forgewrite.fr/(.*)"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.replacement=https://www.forgewrite.fr/$${1}"
      - "traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true"
    networks:
      - forgewrite
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: forgewrite
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: write
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - forgewrite
    restart: unless-stopped

volumes:
  pgdata:

networks:
  forgewrite:
