services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - forgewrite
    depends_on:
      - db
    volumes:
      - ../api:/app
      - ../api/prisma:/app/prisma

  client:
    image: node:18
    working_dir: /app
    volumes:
      - ../client:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - forgewrite
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: forgewrite
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: write
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - forgewrite

volumes:
  pgdata:

networks:
  forgewrite:
