services:
  php:
    build:
      context: ./php
    volumes:
      - ../api:/var/www/api
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=dev
    networks:
      - forgewrite
    depends_on:
      - db

  client:
    image: node:18
    working_dir: /app
    volumes:
      - ../client:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - forgewrite
    depends_on:
      - php

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: forgewrite
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: write
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - forgewrite

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../api/public:/var/www/html
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - forgewrite

volumes:
  pgdata:

networks:
  forgewrite:
