services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: forgewrite
      MYSQL_USER: forge
      MYSQL_PASSWORD: write
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - forgewrite
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - forgewrite
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../api:/app
      - ../api/prisma:/app/prisma

  client:
    image: node:18
    working_dir: /app
    volumes:
      - ../client:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - forgewrite
    depends_on:
      - api

volumes:
  mysqldata:

networks:
  forgewrite:
